apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      volumes:
        - name: nfs-volume
          nfs: 
            server: 10.0.0.63 # Change this!
            path: /san/nfs-fs/exports/export1

      containers:
        - name: httpd
          image: 10.0.0.150:5000/app1:3
          imagePullPolicy: Always
          ports:
          - containerPort: 80

          volumeMounts:
            - name: nfs-volume
              mountPath: /var/www/html

      
