apiVersion: v1
kind: Service
metadata:
  name: httpd2-svc
spec:
  type: LoadBalancer
  selector:
    app: httpd
  ports:
    - name: http2-svc
      protocol: TCP
      port: 80
      targetPort: 80
status:
  loadBalancer:
    ingress:
    - ip: 10.0.0.80
