apiVersion: v1
kind: Service
metadata:
  name: httpd-svc
spec:
  type: NodePort
  selector:
    app: httpd
  ports:
    - name: http-svc
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
