apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: httpd
    spec:
      volumes:
        - name: nfs-volume
          nfs: 
            server: 10.0.0.63 
            path: /san/nfs-fs/exports/export1

      containers:
        - name: httpd
          image: 10.0.0.150:5000/httpd:4
          imagePullPolicy: Always
          ports:
          - containerPort: 80

          volumeMounts:
            - name: nfs-volume
              mountPath: /var/www/html

      
