apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: php
    spec:
      volumes:
        - name: nfs-volume
          glusterfs:
            endpoints: glusterfs-cluster
            path: gfs1

      containers:
        - name: php
          image: 10.0.0.150:5000/php:6
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 9000

          volumeMounts:
            - name: nfs-volume
              mountPath: /var/www/html

      
