apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - name: prometheus-svc
      protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30089
status:
  loadBalancer:
    ingress:
    - ip: 10.0.0.81

