apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
spec:
  type: LoadBalancer
  selector:
    app: prometheus
  ports:
    - name: prometheus-svc
      protocol: TCP
      port: 9090
      targetPort: 9090
