apiVersion: v1
kind: Service
metadata:
  name: tomcat-svc
spec:
  type: NodePort
  selector:
    app: tomcat
  ports:
    - name: tomcat-svc
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30081
